// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jraqnevmivwevhurnlwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyYXFuZXZtaXZ3ZXZodXJubHdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDg0NTgsImV4cCI6MjA3MTQyNDQ1OH0.FgRmS_id-oN2aYbp0NkV0h5AoSpo4RK2lxV_fnB_uf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});